### ISSUE TITLE
Fine Offset UV being interpreted as solar radiation W/m2

### ISSUE THREAD

**Issue by infinityab** [matthewwall/weewx-wh23xx#2]
There seems to be an anomaly with Fine Offset producing 3 values of light namely UVI, UV and Light - the latter as LUX light value. UVI displays correctly although it comes under the label of UV on the Weeewx HTML page. The problem is that the UV value (which is around 3.5 on sunny day) seems to be used directly by Weevx as solar radiation in w/m2 and this can also be seen incorrectly on the wunderground upload as well. I think the solar radiation should be the 'Light' LUX value which is then multiplied by the 0.0079 constant standard to produce the correct w/m2. Log attached.
[wh2310-snippet.txt](https://github.com/matthewwall/weewx-wh23xx/files/672335/wh2310-snippet.txt)

**Comment by matthewwall** [comment]
the wu protocol has two parameters related to sunlight:  solarradiation and UV

solarradiation is measured in watts per square meter
UV is an index

http://wiki.wunderground.com/index.php/PWS_-_Upload_Protocol

according to the wh2300 docs, the hardware reports light in lux (light), radiation in micro-watts per square meter (uv), and uv index as 1-15 (uvi).  it uses a calibration constant in the hardware to convert from lux to radiation (factory setting for this constant is 126.7).

so we should have the following:

```
wh23xx     weewx       wu
light      light       -
uvi        UV          UV
uv         radiation   solarradiation
```

if any calibration has to be applied, i would guess that is a multiplier of 10e-6 to go from the micro-watts per square meter that the wh2300 reports to the watts per square meter that weewx and wu expect for radiation and solarradiation, respectively.

these are the values from wh2310-snippet.txt:

light: 127669.6 lux
uvi: 8
uv: 3.138 uW/m^2

assuming that localtime was, in fact, Dec 24 03:04:03, and the latitude is somewhere temperate, then 3 uW is not unreasonable for uv (radiation), 8 seems high for uvi (i would expect 0), and 127,669 seems high for lux (i would expect close to zero).

have you modified the radiation multiplier on the station hardware?

**Comment by infinityab** [comment]
No changes have been made except to the barometer pressure adjustment. The time given in the snippet is +11 hours out, so 11 hours needs to be added to that. Not sure why that is as the 'date' command on Pi gives the correct time and zone Australian Eastern Summer time (Taree, NSW -31.5 lat) and it is shown correctly on the Weewx page from the Pi. Also the date and time are correct on  the WH2310. 
The constant of 126.7 is the reciprocal of 0.0079 I mentioned so those are virtually identical, just applied slightly differently. The FO WH2310 does display the solar radiation in w/m2 and that works out exactly to the LUX figure divided by the 126.7 constant (or x by .0079).
I couldn't find anything in the WH2310 module display, or manual or on the FOSHK website relating to uW/m^2 so I don't where that uv figure 3.128 is coming from or what it is. At midday here mid-summer wouldn't you expect  a figure of around 1000-1200 w/m2? The docs I have only refer to w/m2.

**Comment by matthewwall** [comment]
so it sounds like the driver should ignore the uv value and use light*0.0079 for radiation instead.

could you verify that the light-to-radiation multiplier on your station is, in fact, 126.7?

**Comment by infinityab** [comment]
Yes can confirm that although sun very low now and changing captured Lux 5082 with 42.1 w/m2 from WH2310 module which comes out to 126.733 so I would say that was spot on.
* note - fixed time issue by also setting raspi-config to locale - I had used this command to set zone and time which works but gives the wrong time in syslog, probably because it's just an offset? -
    $ ln -sf /usr/share/zoneinfo/Australia/Sydney /etc/localtime

**Comment by IridiumXOR** [comment]
Sorry, but i think that there is an error among UV, light and radiation. In the last table here http://www.weewx.com/docs/customizing.htm it's specified that radiation (aka light not UV) should be expressed in watt/m2 in all the measure systems. So I think it's better to rename LIGHT -> RADIATION (converted from lux to w/m2 using internal factor), UV ->UVI and use another indicator for the measure of UV (as UVR). RADIATION and UVI are saved inside the weewx database as hystorical data while, at the moment, light is not be saved

**Comment by matthewwall** [comment]
@oliveriandrea: light and radiation are not the same thing!  light is luminosity, measured in lux.  radiation is solar radiation, measured in watt/m^2.  the conversion factor of 0.0079 is a very rough approximation for the conversion between lux and watt/m^2.

i was hoping that the wh23xx would actually measure solar radiation AND lux AND uv.  however, it sounds like it measures only lux, then the firmware does some maths to produce uv and uvi.  and it sounds like the uv number that it produces is not correct.

it would help to have more data!  please provide the raw light, uv, and uvi values as presented by the driver (from the LOOP packets) and the equivalent values from the console display. 5 or 10 samples from different times of day would help.  also include your latitude and longitude, and the time of day of each sample.

i suspect that we will end up with a driver that emits light, radiation, and uv as light, light*0.0079, and uvi from the hardware.

meanwhile, as a short-term fix you can put this in weewx.conf:
```
[StdCalibration]
    [[Corrections]]
        radiation = light * 0.0079
```

m

**Comment by infinityab** [comment]
There are actually **two light sensors** on the outside station plus the solar cell. One sensor has a domed opaque white filter so presumably that is for Light/Lux and the other has a clear diffused filter presumably for the UVI calculation. The so called UV approx. 3.5 value we get at full sun presumably is the output from the diffused filter sensor? The w/m^2 on the module is clearly derived from the Light/LUX value by internal calculation as the w/^2 value is exactly the LUX * 0.0079 which as you said is just an approximation of the expected various bands of light but is the accepted method if no other available. 

Not sure what you mean by 'loop packets' but I'll cut out the relevant bits hourly.
It's dull here now after some very hot weather but I will nevertheless take the samples, if they are no good I can repeat on a better day.

**Comment by matthewwall** [comment]
does your solar sensor look like this:

http://lancet.mit.edu/mwall/projects/weather/wh23xx-solar-sensor-1.png

http://lancet.mit.edu/mwall/projects/weather/wh23xx-solar-sensor-2.png

when you run weewx directly (rather than as a daemon), it will spit out LOOP packets every time it reads the sensors (nominally every 15 seconds), and REC archive record every archive interval (nominally every 5 minutes).

we want to match up the LOOP data with whatever you see on the console, since the REC data is an average of multiple LOOP.  REC should be close, but LOOP should be more accurate.

days are starting to get longer here, but we're a long way from any significant solar radiation for testing.

**Comment by infinityab** [comment]
Yep that's the one. OK I will upload the trimmed file in about 7 hours.

**Comment by infinityab** [comment]
OK attached is hourly data taken from WH23xx Syslog today. Not a lot of sun just the odd bright spot.
[WH23xx-hourly-Jan-03.txt](https://github.com/matthewwall/weewx-wh23xx/files/681878/WH23xx-hourly-Jan-03.txt)

**Comment by infinityab** [comment]
Reopened

**Comment by matthewwall** [comment]
thanks for that dave!  i updated the driver so that radiation is now derived from luminosity.  this probably should happen in StdWXCalculate instead of in the driver.  i also noticed that the raw 'uv' (not uvi) from the hardware is divided by 1000 (as per the fine offset documentation).  so i'm still not sure exactly what 'uv' is coming from the hardware.

**Comment by infinityab** [comment]
No problem. Maybe it's the PV cell voltage? I will try masking the sensors and PV individually to see what drops out - when the rain stops.

**Comment by infinityab** [comment]
Here are the results of covering the two sensors and PV cell one at a time.
[WH23XX-Sensor-Tests.txt](https://github.com/matthewwall/weewx-wh23xx/files/683913/WH23XX-Sensor-Tests.txt)
When the Opaque white filter was covered the FO modules w/m2 also dropped accordingly.

**Comment by IridiumXOR** [comment]
Why do not you use the internal lux to w/m2 factor burned into the eeproom? Maybe if Fine Offset will change the radiation sensor the software defined conversion factor will be wrong. Probably if radiation sensor will change (in future hardware release)  Fine Offset will change also the internal burned conversion factor..

**Comment by matthewwall** [comment]
the conversion from lux to W/m^2 is an approximation.  if someone needs to adjust that multiplier because they are closer to the equator or closer to the poles, it is much easier to do so in a weewx configuration.
