### ISSUE TITLE
Driver Version

### ISSUE THREAD

**Issue by infinityab** [matthewwall/weewx-wh23xx#4]
Is it possible to add the driver version # to the debug info generated in Syslog?

**Comment by matthewwall** [comment]
you should see a line in syslog like this:

wh23xx: driver version is 0.11

during startup when weewx loads the driver

**Comment by infinityab** [comment]
Mmm but that's not much use in a Syslog that you might receive from someone about a driver issue - wouldn't you want to know for sure which driver they were using?

**Comment by matthewwall** [comment]
are you suggesting that the driver version should be in every message that is sent to syslog?

**Comment by infinityab** [comment]
Well how else can you tell whether a syslog that has been forwarded with an issue is actually using the driver that the submitter says it is? It is quite easy in these early stages of many driver updates and tweaks for the user to get mixed up with the copying of one driver over another rather than constantly going through the install process (yes I've done that myself). Unless there is another way, afterall it's not much different to putting the date and time on every single entry, just another identity tag.
