### ISSUE TITLE
Crashing weewx when Solar sensors lose connection

### ISSUE THREAD

**Issue by AmpacheUser** [matthewwall/weewx-wh23xx#5]
It appears that when the Solar Sensors go offline this driver crashes weewx with the following error.
No other sensors went offline at the time. I got the solar sensor back up and everything started working again. Unsure what would happen if any of the other sensors went down. I wonder if there can be any error handling added to avoid the crash.

Traceback (most recent call last):
File "/usr/bin/weewxd", line 64, in 
weewx.engine.main(options, args)
File "/usr/share/weewx/weewx/engine.py", line 847, in main
engine.run()
File "/usr/share/weewx/weewx/engine.py", line 186, in run
for packet in self.console.genLoopPackets():
File "/usr/share/weewx/user/wh23xx.py", line 421, in genLoopPackets
packet = self._data_to_packet(decoded)
File "/usr/share/weewx/user/wh23xx.py", line 469, in _data_to_packet
pkt['radiation'] = pkt['luminosity'] * LUMINOSITY_TO_RADIATION
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Here is the last data point before the crash:
LOOP: 2017-01-23 18:45:00 GST (1485222300) altimeter: 29.7772633607, appTemp: 53.6055562095, barometer: 29.7948270007, cloudbase: 1543.95712939, dateTime: 1485222300, dewpoint: 51.6653886307, heatindex: 53.06, humidex: 56.1517736111, inDewpoint: 47.1926169982, inHumidity: 38, inTemp: 74.48, luminosity: 0.0, maxSolarRad: None, outHumidity: 95, outTemp: 53.06, outTempDay: None, outTempNight: 53.06, pressure: 28.4875789413, radiation: 0.0, rain: 0.0, rainRate: 0, usUnits: 1, UV: 0, uv_raw: 0, windchill: 53.06, windDir: None, windGust: 0.0, windGustDir: None, windSpeed: 0.0

**Comment by matthewwall** [comment]
fixed in v0.12 at commit 023ffa8

**Comment by AmpacheUser** [comment]
Now I get the following error:

Traceback (most recent call last):
  File "/usr/bin/weewxd", line 64, in <module>
    weewx.engine.main(options, args)
  File "/usr/share/weewx/weewx/engine.py", line 841, in main
    engine = engine_class(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 70, in __init__
    self.setupStation(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 94, in setupStation
    __import__(driver)
  File "/usr/share/weewx/user/wh23xx.py", line 469
    pkt['radiation'] = pkt['luminosity'] * LUMINOSITY_TO_RADIATION if pkt['luminosity' is not None else None
                                                                                                                                                               ^
SyntaxError: invalid syntax

![error](https://cloud.githubusercontent.com/assets/17130928/22232320/ee18505c-e1a5-11e6-85ea-b60dd1242d8e.png)

Bracket Missing?

**Comment by matthewwall** [comment]
sorry.  typo.  fixed at fc598de
