### ISSUE TITLE
TP2700 protocol documentation

### ISSUE THREAD

**Issue by RrPt** [matthewwall/weewx-wh23xx#7]
Hello Matthew,

i have a weather station WS980, and it seems, it uses the same protocol like TP2700.
I want to implemet the protocol for myself and search for a documentation.
In your code you wrote:

**Based on the protocol specified in "TP2700 EEPROM data structure" V1.0 with
serial number FOS-ENG-022-A for model WH2300, and "TP2700 PC Protocol".**

Can you tell me, where this documentation is available?
A google search gets no hits.

Regards 
Rainer

**Comment by matthewwall** [comment]
hello! i received the documentation from an employee at fine offset in 2015.  they are mostly in chinese, so i had to use google translate to make sense of it.  unfortunately FO did not give me permission to distribute the documents, and my brief interactions with that employee were cut off by management.  you could try contacting them directly:

http://www.foshk.com/about.html

good luck!

**Comment by matthewwall** [comment]
hey, i just found old links to the docs from a weewx user.  don't know if the files are still there, but you could give it a try:

https://groups.google.com/forum/#!msg/weewx-user/MlkTnmbDLOc/Gxa4pgk0rBYJ

**Comment by matthewwall** [comment]
and you are in luck!  here is a working link to the docs.  not sure if it is the same version i had.  i found the docs somewhat useful, but i had to do a lot of usb sniffing to actually get things to work.

https://www.lloydkinsella.net/2016/09/26/my-first-weather-station/

**Comment by RrPt** [comment]
Hello Matthew,

 

thank you very much for this info. This helps me a lot

The outer protocoll ist different, because info goes over WiFi instead of USB, but the CMD und Eprom data ist he same.

 

Regards

Rainer

 

Von: Matthew Wall <notifications@github.com> 
Gesendet: Samstag, 16. Februar 2019 23:23
An: matthewwall/weewx-wh23xx <weewx-wh23xx@noreply.github.com>
Cc: RrPt <R.Petzoldt@web.de>; Author <author@noreply.github.com>
Betreff: Re: [matthewwall/weewx-wh23xx] TP2700 protocol documentation (#7)

 

and you are in luck! here is a working link to the docs. not sure if it is the same version i had. i found the docs somewhat useful, but i had to do a lot of usb sniffing to actually get things to work.

https://www.lloydkinsella.net/2016/09/26/my-first-weather-station/
